bq-dbt-workshop:
  outputs:
    dev:
      dataset: trips_data_all
      fixed_retries: 1
      keyfile: /.google/credentials/google_credentials.json
      location: europe-west2
      method: service-account
      priority: interactive
      project: pacific-card-374422
      threads: 4
      timeout_seconds: 300
      type: bigquery
  target: dev
